name = "rss-translater"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Cron triggers for feed updates
[triggers]
crons = ["*/30 * * * *"]

# Environment variables
[vars]
ENVIRONMENT = "production"
DEFAULT_TARGET_LANGUAGE = "Chinese Simplified"
LOG_LEVEL = "INFO"

# D1 Database configuration
# Note: When deploying via Dashboard, configure these bindings in the UI
[[d1_databases]]
binding = "DB"
database_name = "rss-translator"
database_id = ""  # Will be set by Dashboard deployment

# KV Storage configuration  
# Note: When deploying via Dashboard, configure these bindings in the UI
[[kv_namespaces]]
binding = "CACHE"
id = ""  # Will be set by Dashboard deployment

# Required secrets (set via Dashboard or wrangler secret put):
# - OPENAI_API_KEY (optional)
# - DEEPL_API_KEY (optional) 
# - FIELD_ENCRYPTION_KEY (required for production)