name = "rss-translator-worker"
main = "src/index.js"
compatibility_date = "2024-08-18"
compatibility_flags = ["nodejs_compat"]

# Cron triggers for feed updates
[triggers]
crons = ["*/30 * * * *"]

# Environment variables
[vars]
ENVIRONMENT = "production"
DEFAULT_TARGET_LANGUAGE = "Chinese Simplified"
LOG_LEVEL = "INFO"

# Note: D1 databases, KV namespaces, and secrets should be configured
# through the Cloudflare Dashboard when deploying via GitHub integration
# 
# Required bindings:
# - D1 Database: binding name "DB"
# - KV Namespace: binding name "CACHE"
#
# Required secrets:
# - OPENAI_API_KEY (optional)
# - DEEPL_API_KEY (optional) 
# - FIELD_ENCRYPTION_KEY (required for production)