name = "rss-translater"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Custom domain routes
[[routes]]
pattern = "r.samsoncj.xyz/*"
zone_name = "samsoncj.xyz"

# Cron triggers for feed updates
[triggers]
crons = ["*/30 * * * *"]

# Environment variables
[vars]
ENVIRONMENT = "production"
DEFAULT_TARGET_LANGUAGE = "Chinese Simplified"
LOG_LEVEL = "INFO"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "rss-translator"
database_id = "505bce6e-5289-49cc-8613-560c3086096f"

# KV Storage configuration  
[[kv_namespaces]]
binding = "CACHE"
id = "fb058dac8a20401bb55ea18c4c06bd6a"

# Required secrets (set via Dashboard or wrangler secret put):
# - OPENAI_API_KEY (optional)
# - DEEPL_API_KEY (optional) 
# - FIELD_ENCRYPTION_KEY (required for production)